const NEW_REQUEST = 'NEW_REQUEST';
const REFETCH_CHAT = 'REFETCH_CHAT';
const NEW_MESSAGE = 'NEW_MESSAGE';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';

module.exports = {
    NEW_REQUEST, REFETCH_CHAT, NEW_MESSAGE
}